/* This file was generated by syncqt. */
#ifndef QT_QTOPENGL_VERSION_H
#define QT_QTOPENGL_VERSION_H

#define QTOPENGL_VERSION_STR "5.15.13"

#define QTOPENGL_VERSION 0x050F0D

#endif // QT_QTOPENGL_VERSION_H
